# coding=utf-8
# *** WARNING: this file was generated by Pulumi SDK Generator. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import copy
import warnings
import pulumi
import pulumi.runtime
from typing import Any, Mapping, Optional, Sequence, Union, overload
from .. import _utilities
from ._enums import *

__all__ = [
    'ClusterAddonsIngressArgsArgs',
    'ClusterAddonsIngressItemArgsArgs',
    'IngressNginxTlsArgsArgs',
]

@pulumi.input_type
class ClusterAddonsIngressArgsArgs:
    def __init__(__self__, *,
                 admin: Optional[pulumi.Input['ClusterAddonsIngressItemArgsArgs']] = None,
                 enabled: Optional[pulumi.Input[bool]] = None,
                 global_: Optional[pulumi.Input['ClusterAddonsIngressItemArgsArgs']] = None):
        """
        :param pulumi.Input['ClusterAddonsIngressItemArgsArgs'] admin: Configure the admin IngressController.
        :param pulumi.Input[bool] enabled: Enable the IngressControllers.
        :param pulumi.Input['ClusterAddonsIngressItemArgsArgs'] global_: Configure the global IngressController.
        """
        if admin is not None:
            pulumi.set(__self__, "admin", admin)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)
        if global_ is not None:
            pulumi.set(__self__, "global_", global_)

    @property
    @pulumi.getter
    def admin(self) -> Optional[pulumi.Input['ClusterAddonsIngressItemArgsArgs']]:
        """
        Configure the admin IngressController.
        """
        return pulumi.get(self, "admin")

    @admin.setter
    def admin(self, value: Optional[pulumi.Input['ClusterAddonsIngressItemArgsArgs']]):
        pulumi.set(self, "admin", value)

    @property
    @pulumi.getter
    def enabled(self) -> Optional[pulumi.Input[bool]]:
        """
        Enable the IngressControllers.
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "enabled", value)

    @property
    @pulumi.getter(name="global")
    def global_(self) -> Optional[pulumi.Input['ClusterAddonsIngressItemArgsArgs']]:
        """
        Configure the global IngressController.
        """
        return pulumi.get(self, "global_")

    @global_.setter
    def global_(self, value: Optional[pulumi.Input['ClusterAddonsIngressItemArgsArgs']]):
        pulumi.set(self, "global_", value)


@pulumi.input_type
class ClusterAddonsIngressItemArgsArgs:
    def __init__(__self__, *,
                 enable_tls_termination: Optional[pulumi.Input[bool]] = None,
                 public: Optional[pulumi.Input[bool]] = None,
                 whitelist: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]] = None):
        """
        :param pulumi.Input[bool] enable_tls_termination: Enable TLS termination in Load Balancer.
        :param pulumi.Input[bool] public: Use a public Load Balancer to expose the IngressController.
        :param pulumi.Input[Sequence[pulumi.Input[str]]] whitelist: Set a whitelist to access the IngressController.
        """
        if enable_tls_termination is not None:
            pulumi.set(__self__, "enable_tls_termination", enable_tls_termination)
        if public is not None:
            pulumi.set(__self__, "public", public)
        if whitelist is not None:
            pulumi.set(__self__, "whitelist", whitelist)

    @property
    @pulumi.getter(name="enableTlsTermination")
    def enable_tls_termination(self) -> Optional[pulumi.Input[bool]]:
        """
        Enable TLS termination in Load Balancer.
        """
        return pulumi.get(self, "enable_tls_termination")

    @enable_tls_termination.setter
    def enable_tls_termination(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "enable_tls_termination", value)

    @property
    @pulumi.getter
    def public(self) -> Optional[pulumi.Input[bool]]:
        """
        Use a public Load Balancer to expose the IngressController.
        """
        return pulumi.get(self, "public")

    @public.setter
    def public(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "public", value)

    @property
    @pulumi.getter
    def whitelist(self) -> Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]:
        """
        Set a whitelist to access the IngressController.
        """
        return pulumi.get(self, "whitelist")

    @whitelist.setter
    def whitelist(self, value: Optional[pulumi.Input[Sequence[pulumi.Input[str]]]]):
        pulumi.set(self, "whitelist", value)


@pulumi.input_type
class IngressNginxTlsArgsArgs:
    def __init__(__self__, *,
                 domain: pulumi.Input[str],
                 zone_id: pulumi.Input[str],
                 enabled: Optional[pulumi.Input[bool]] = None):
        """
        :param pulumi.Input[str] domain: The domain to be used to create a signed Certificate.
        :param pulumi.Input[str] zone_id: The Zone id.
        :param pulumi.Input[bool] enabled: Enable the signed Certificate.
        """
        pulumi.set(__self__, "domain", domain)
        pulumi.set(__self__, "zone_id", zone_id)
        if enabled is not None:
            pulumi.set(__self__, "enabled", enabled)

    @property
    @pulumi.getter
    def domain(self) -> pulumi.Input[str]:
        """
        The domain to be used to create a signed Certificate.
        """
        return pulumi.get(self, "domain")

    @domain.setter
    def domain(self, value: pulumi.Input[str]):
        pulumi.set(self, "domain", value)

    @property
    @pulumi.getter(name="zoneId")
    def zone_id(self) -> pulumi.Input[str]:
        """
        The Zone id.
        """
        return pulumi.get(self, "zone_id")

    @zone_id.setter
    def zone_id(self, value: pulumi.Input[str]):
        pulumi.set(self, "zone_id", value)

    @property
    @pulumi.getter
    def enabled(self) -> Optional[pulumi.Input[bool]]:
        """
        Enable the signed Certificate.
        """
        return pulumi.get(self, "enabled")

    @enabled.setter
    def enabled(self, value: Optional[pulumi.Input[bool]]):
        pulumi.set(self, "enabled", value)


