name: integration-tests

on:
  workflow_dispatch:

jobs:
  build:
    name: Ingregration tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run tests
      run: make integration_tests
