name: release

on:
  push:
    tags:
      - v*.*.*

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  #  publish_binary:
  #    name: publish
  #    runs-on: macos-12
  #    steps:
  #      - name: Checkout Repo
  #        uses: actions/checkout@v2
  #      - name: Unshallow clone for tags
  #        run: git fetch --prune --unshallow --tags
  #      - name: Setup Node
  #        uses: actions/setup-node@v1
  #        with:
  #          node-version: ${{matrix.nodeversion}}
  #      - name: Install pulumictl
  #        uses: jaxxstorm/action-install-gh-release@v1.5.0
  #        with:
  #          repo: pulumi/pulumictl
  #      - name: Install Pulumi CLI
  #        uses: pulumi/action-install-pulumi-cli@v1.0.1
  #      - name: Create Provider Binaries
  #        run: make dist
  #      - name: Create GH Release
  #        uses: softprops/action-gh-release@v1
  #        with:
  #          files: |
  #            dist/*.tar.gz
  #    strategy:
  #      fail-fast: true
  #      matrix:
  #        nodeversion:
  #          - 16.x

  publish_sdk:
    name: publish
    runs-on: macos-12
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Unshallow clone for tags
        run: git fetch --prune --unshallow --tags
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: ${{matrix.nodeversion}}
      - name: Install pulumictl
        uses: jaxxstorm/action-install-gh-release@v1.5.0
        with:
          repo: pulumi/pulumictl
      - name: Install Pulumi CLI
        uses: pulumi/action-install-pulumi-cli@v1.0.1
      - name: Create SDK
        run: make build_nodejs_sdk
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm publish
        working-directory: ./sdk/nodejs/bin
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
